export enum PURCHASE_ERROR {
  PURCHASE_NOT_FOUND = 'PURCHASE_NOT_FOUND',
  PRODUCT_WAS_PURCHASED = 'PRODUCT_WAS_PURCHASED',
  MINIMUM_COUNT_IS = 'MINIMUM_COUNT_IS',
  MINIMUM_LENGTH_IS = 'MINIMUM_LENGTH_IS',
  COUNT_GREATER_MAXIMUM = 'COUNT_GREATER_MAXIMUM',
  LENGTH_GREATER_MAXIMUM = 'LENGTH_GREATER_MAXIMUM',
  MASTER_CLASS_SUBSCRIPTION_EXPIRED = 'MASTER_CLASS_SUBSCRIPTION_EXPIRED',
}
