export enum AUTH_ERROR {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WRONG_PASSWORD_OR_LOGIN = 'WRONG_PASSWORD_OR_LOGIN',
  WRONG_CODE = 'WRONG_CODE',
  WRONG_NEW_CODE = 'WRONG_NEW_CODE',
  WRONG_OLD_CODE = 'WRONG_OLD_CODE',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
